server:
  port: 8080

spring:
  application:
    name: backend
  
  datasource:
    url: jdbc:mysql://34.47.64.102:3306/admin?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update # 개발 시 `update`, 운영 시 `validate` 또는 `none` 추천
  
  sql:
    init:
      mode: always
  # H2 콘솔 (테스트용)
  
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: 34.47.64.102
      port: 6379
      timeout: 2000
      
  # jwt

jwt:
  expiration_time: 86400000 #1일
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  
   
    
    
    