server:
  port: 8080

spring:
  application:
    name: backend

  cache:
    type: simple # 개발 환경에서는 simple 사용

  data:
    redis:
      host: 34.47.64.102
      port: 6379
      timeout: 2000

  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: update # or update, create-drop, validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

   

jwt:
  expiration_time: 86400000
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
 